#!/usr/bin/env bash
set -euo pipefail

# Prepare a *target-side* Python layout for cross-building grpcio.
#
# Downloads CPython public headers from GitHub (reliable across all version
# tags) so that a cross-compiled extension can actually use Python.h.
#
# This still does NOT build the full CPython interpreter for the target; it
# is a practical middle step between "no headers" and "full CPython bootstrap".

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build"
TARGET_PYTHON_VERSION="${PYTHON_VERSION:-${TARGET_PYTHON_VERSION:-3.12}}"
PYTHON_TARGET="$BUILD_DIR/python-target-aarch64"

mkdir -p "$PYTHON_TARGET/include" "$PYTHON_TARGET/lib" "$PYTHON_TARGET/bin"

cat > "$PYTHON_TARGET/python-target.env" <<EOF
TARGET_PYTHON_VERSION=${TARGET_PYTHON_VERSION}
TARGET_PYTHON_ABI=cp${TARGET_PYTHON_VERSION}
TARGET_PYTHON_PLATFORM=termux-aarch64
PYTHON_TARGET=${PYTHON_TARGET}
EOF

# Determine full CPython patch version
case "$TARGET_PYTHON_VERSION" in
  3.13) CPYTHON_FULL_VERSION="3.13.3" ;;
  3.12) CPYTHON_FULL_VERSION="3.12.7" ;;
  3.11) CPYTHON_FULL_VERSION="3.11.9" ;;
  3.10) CPYTHON_FULL_VERSION="3.10.14" ;;
  *)
    CPYTHON_FULL_VERSION="${TARGET_PYTHON_VERSION}0"
    echo "[termux-python] WARNING: using guessed full version ${CPYTHON_FULL_VERSION}"
    ;;
esac

echo "[termux-python] targeting CPython ${CPYTHON_FULL_VERSION}"

if [ -f "$PYTHON_TARGET/include/Python.h" ]; then
  echo "[termux-python] Python.h already present, skipping download"
else
  # Use GitHub CPython source tarball - always available for any tag
  CPYTHON_TAG="v${CPYTHON_FULL_VERSION}"
  CPYTHON_TARBALL="$BUILD_DIR/cpython-${CPYTHON_TAG}.tar.gz"
  CPYTHON_URL="https://github.com/python/cpython/archive/refs/tags/${CPYTHON_TAG}.tar.gz"

  echo "[termux-python] downloading ${CPYTHON_URL}"
  if [ ! -f "$CPYTHON_TARBALL" ]; then
    curl -fsSL --retry 3 --retry-delay 5 -o "$CPYTHON_TARBALL" "$CPYTHON_URL"
  fi

  echo "[termux-python] extracting headers only"
  # GitHub tarball top-level dir is cpython-<version> (no 'v')
  CPYTHON_SRC_DIR="$BUILD_DIR/cpython-${CPYTHON_FULL_VERSION}"
  if [ ! -d "$CPYTHON_SRC_DIR" ]; then
    tar -xzf "$CPYTHON_TARBALL" -C "$BUILD_DIR"
    # The extracted dir name matches the tag without 'v'
    if [ -d "$BUILD_DIR/cpython-${CPYTHON_TAG}" ]; then
      mv "$BUILD_DIR/cpython-${CPYTHON_TAG}" "$CPYTHON_SRC_DIR"
    fi
  fi

  if [ ! -d "$CPYTHON_SRC_DIR/Include" ]; then
    echo "[termux-python] ERROR: ${CPYTHON_SRC_DIR}/Include not found"
    ls "$CPYTHON_SRC_DIR/" 2>/dev/null | head -n 30
    exit 1
  fi

  # Copy headers into our target layout
  cp -rf "$CPYTHON_SRC_DIR/Include/"* "$PYTHON_TARGET/include/"

  # Verify
  if [ ! -f "$PYTHON_TARGET/include/Python.h" ]; then
    echo "[termux-python] ERROR: Python.h not found after copy"
    exit 1
  fi

  # CPython does NOT ship pyconfig.h in source; it is generated by configure.
  # For cross-compile we write a minimal one matching Linux aarch64.
  if [ ! -f "$PYTHON_TARGET/include/pyconfig.h" ]; then
    cat > "$PYTHON_TARGET/include/pyconfig.h" <<'PYCONF'
/* Minimal pyconfig.h for aarch64 Linux/Android cross-compile.
   NOT a full generated config - just enough for Python.h to compile. */
#ifndef Py_PYCONFIG_H
#define Py_PYCONFIG_H

/* --- platform --- */
#define SIZEOF_SHORT      2
#define SIZEOF_INT        4
#define SIZEOF_LONG       8
#define SIZEOF_LONG_LONG  8
#define SIZEOF_OFF_T      8
#define SIZEOF_VOID_P     8
#define SIZEOF_SIZE_T     8
#define SIZEOF_PTHREAD_T  8
#define SIZEOF_FLOAT      4
#define SIZEOF_DOUBLE     8

#define SIZEOF_WCHAR_T    4
#define SIZEOF_UNSIGNED_LONG  8

#define PGPYGETPEER_HAVE_ARG 1
#define PGPYSYSCALL_DEFINE 0

#define PY_SET_GET_GROUP_ID 1
#define PY_SET_GET_GROUP_NAME 1
#define PY_SET_GET_USER_NAME  1

#define PGPYSHGETPEER_HAVE_ARG 1

#define HAVE_FSEEKO 1
#define HAVE_PREAD  1
#define HAVE_PWRITE 1

#define HAVE_READLINE  0
#define HAVE_LIB_READLINE 0

#define HAVE_CLOCK  1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_SELECT   1

#define HAVE_SIGACTION 1
#define HAVE_SIGADDSET 1
#define HAVE_SIGEMPTY 1
#define HAVE_SIGISMEMBER 1

#define HAVE_SETVBUF 1
#define HAVE_VSNPRINTF 1
#define HAVE_SNPRINTF 1

#define HAVE_ATAN2  1
#define HAVE_COSH   1
#define HAVE_EXPF   1
#define HAVE_LOG10  1
#define HAVE_LOG2   1
#define HAVE_SINH   1
#define HAVE_TANH   1

#define HAVE_FLOOR  1
#define HAVE_CEIL   1
#define HAVE_TRUNC  1

#define HAVE_SBRK   0
#define HAVE_GETPWUID 1
#define HAVE_INITGROUPS 1
#define HAVE_GETGRENT_R 1
#define HAVE_GETPWENT_R 1
#define HAVE_GETPWNAM_R 1
#define HAVE_GETGRNAM_R 1

#define HAVE_NANOSLEEP 1

#define HAVE_TM_GMtoff 1
#define HAVE_TM_ZONE  1

#define HAVE_SYSLOG_H 1

#define HAVE_SYS_STATVFS 1
#define HAVE_SYS_STATFS 1

#define DEFAULT_PY_LOG 1
#define MAX_SIZEOF_PYTHON  512

/* --- endianness (aarch64 = little-endian) --- */
#define WORDS_BIGENDIAN 0

/* --- type definitions --- */
#define PY_SSIZE_T_CLEAN 1
#define PY_CTOR_REF_UNSAFE  0

#define LONG_BIT 64
#define WORD_BIT 32

/* --- misc --- */
#define HAVE_FCNTL_H      1
#define HAVE_SYS_TIMEB_H  0
#define HAVE_UNISTD_H     1
#define HAVE_FCNTL        1
#define HAVE_POLL_H       1
#define HAVE_POLL         1
#define HAVE_SYS_EPOLL_H  1
#define HAVE_SYS_INOTIFY_H 1
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_SYS_TIMERFD_H 1
#define HAVE_SYS_SIGNALED 0

#define HAVE_DIRENT_H     1
#define HAVE_SYS_DIR_H    0

#define FILE_EXT_MODULES  "modules.so"
#define PREFIX  "/usr/local"
#define EXEC_PREFIX "/usr/local"

/* --- Python build flags --- */
#define WITH_PYMALLOC 1
#define HAVE_MEMSET  1
#define HAVE_BUILTIN_ROUND 1

/* --- CPython public API version --- */
#define C_PYTHONAPI  1

/* --- misc defines needed by Python.h --- */
#define HAVE_STDINT_H   1
#define HAVE_STDLIB_H   1
#define HAVE_ERRNO_H    1
#define HAVE_STRING_H   1
#define HAVE_TIME_H     1
#define HAVE_SIGNAL_H   1
#define HAVE_UNISTD_H   1
#define HAVE_LIMITS_H   1

/* --- C language features --- */
#define COMPILER "gcc"
#define SIZEOF_VOID_P 8
#define SIZEOF_OFF_T  8
#define SIZEOF_LONG   8
#define SIZEOF_LONG_LONG 8

/* --- endianness / alignment --- */
#define SIZEOF_MAX_ALIGN_T 8

/* --- locale --- */
#define HAVE_LC_NUMERIC 1
#define HAVE_LC_TIME    1

/* --- sockets / network --- */
#define HAVE_STRUCT_SOCKADDR_SA 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETDB_H      1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_ARPA_INET_H 1

/* --- threads --- */
#define HAVE_PTHREAD_H  1
#define PY_THREAD_LOCAL 0

/* --- Android / Bionic specific --- */
#define ANDROID_API_LEVEL 23
#define HAVE_ANDROID_GETDEVDIR 1

#endif /* Py_PYCONFIG_H */
PYCONF
    echo "[termux-python] minimal pyconfig.h generated for aarch64 cross-compile"
  fi

  echo "[termux-python] headers staged at $PYTHON_TARGET/include"
fi

# Provide a python-config style helper for later source-ing
cat > "$PYTHON_TARGET/bin/python-config" <<EOF
#!/usr/bin/env bash
# Minimal python-config helper for cross-build scaffolding.
set -euo pipefail
case "\${1:-}" in
  --includes)
    echo "-I\$($PYTHON_TARGET/include)"
    ;;
  --ldflags)
    echo "-L\$($PYTHON_TARGET/lib)"
    ;;
  --prefix)
    echo "$PYTHON_TARGET"
    ;;
  --cflags)
    echo "-I\$($PYTHON_TARGET/include)"
    ;;
  *)
    echo "unsupported flag: \${1:-}" >&2
    exit 2
    ;;
esac
EOF
chmod +x "$PYTHON_TARGET/bin/python-config"

echo "[termux-python] target Python layout ready with real headers"
